//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTwitter.ServiceFavorite {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceFavorite.IFavoritesOperations")]
    public interface IFavoritesOperations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFavoritesOperations/FavoriteAdd", ReplyAction="http://tempuri.org/IFavoritesOperations/FavoriteAddResponse")]
        bool FavoriteAdd(int TweetID, int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFavoritesOperations/FavoriteAdd", ReplyAction="http://tempuri.org/IFavoritesOperations/FavoriteAddResponse")]
        System.Threading.Tasks.Task<bool> FavoriteAddAsync(int TweetID, int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFavoritesOperations/FavoriteDelete", ReplyAction="http://tempuri.org/IFavoritesOperations/FavoriteDeleteResponse")]
        bool FavoriteDelete(int TweetID, int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFavoritesOperations/FavoriteDelete", ReplyAction="http://tempuri.org/IFavoritesOperations/FavoriteDeleteResponse")]
        System.Threading.Tasks.Task<bool> FavoriteDeleteAsync(int TweetID, int UserID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFavoritesOperationsChannel : MVCTwitter.ServiceFavorite.IFavoritesOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FavoritesOperationsClient : System.ServiceModel.ClientBase<MVCTwitter.ServiceFavorite.IFavoritesOperations>, MVCTwitter.ServiceFavorite.IFavoritesOperations {
        
        public FavoritesOperationsClient() {
        }
        
        public FavoritesOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FavoritesOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FavoritesOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FavoritesOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool FavoriteAdd(int TweetID, int UserID) {
            return base.Channel.FavoriteAdd(TweetID, UserID);
        }
        
        public System.Threading.Tasks.Task<bool> FavoriteAddAsync(int TweetID, int UserID) {
            return base.Channel.FavoriteAddAsync(TweetID, UserID);
        }
        
        public bool FavoriteDelete(int TweetID, int UserID) {
            return base.Channel.FavoriteDelete(TweetID, UserID);
        }
        
        public System.Threading.Tasks.Task<bool> FavoriteDeleteAsync(int TweetID, int UserID) {
            return base.Channel.FavoriteDeleteAsync(TweetID, UserID);
        }
    }
}
