//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFTwitter
{
    using System;
    
    public partial class GetTweets_Result1
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Tweet { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int FavoritesCount { get; set; }
    }
}
