//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTwitter.ServiceTweet {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTweets_Result1", Namespace="http://schemas.datacontract.org/2004/07/WCFTwitter")]
    [System.SerializableAttribute()]
    public partial class GetTweets_Result1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FavoritesCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TweetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FavoritesCount {
            get {
                return this.FavoritesCountField;
            }
            set {
                if ((this.FavoritesCountField.Equals(value) != true)) {
                    this.FavoritesCountField = value;
                    this.RaisePropertyChanged("FavoritesCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tweet {
            get {
                return this.TweetField;
            }
            set {
                if ((object.ReferenceEquals(this.TweetField, value) != true)) {
                    this.TweetField = value;
                    this.RaisePropertyChanged("Tweet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTweet.ITweetOperations")]
    public interface ITweetOperations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITweetOperations/TweetDelete", ReplyAction="http://tempuri.org/ITweetOperations/TweetDeleteResponse")]
        bool TweetDelete(int UserID, int TweetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITweetOperations/TweetDelete", ReplyAction="http://tempuri.org/ITweetOperations/TweetDeleteResponse")]
        System.Threading.Tasks.Task<bool> TweetDeleteAsync(int UserID, int TweetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITweetOperations/TweetSend", ReplyAction="http://tempuri.org/ITweetOperations/TweetSendResponse")]
        bool TweetSend(int UserID, string tweet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITweetOperations/TweetSend", ReplyAction="http://tempuri.org/ITweetOperations/TweetSendResponse")]
        System.Threading.Tasks.Task<bool> TweetSendAsync(int UserID, string tweet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITweetOperations/TweetView", ReplyAction="http://tempuri.org/ITweetOperations/TweetViewResponse")]
        MVCTwitter.ServiceTweet.GetTweets_Result1[] TweetView(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITweetOperations/TweetView", ReplyAction="http://tempuri.org/ITweetOperations/TweetViewResponse")]
        System.Threading.Tasks.Task<MVCTwitter.ServiceTweet.GetTweets_Result1[]> TweetViewAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITweetOperationsChannel : MVCTwitter.ServiceTweet.ITweetOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TweetOperationsClient : System.ServiceModel.ClientBase<MVCTwitter.ServiceTweet.ITweetOperations>, MVCTwitter.ServiceTweet.ITweetOperations {
        
        public TweetOperationsClient() {
        }
        
        public TweetOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TweetOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TweetOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TweetOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool TweetDelete(int UserID, int TweetID) {
            return base.Channel.TweetDelete(UserID, TweetID);
        }
        
        public System.Threading.Tasks.Task<bool> TweetDeleteAsync(int UserID, int TweetID) {
            return base.Channel.TweetDeleteAsync(UserID, TweetID);
        }
        
        public bool TweetSend(int UserID, string tweet) {
            return base.Channel.TweetSend(UserID, tweet);
        }
        
        public System.Threading.Tasks.Task<bool> TweetSendAsync(int UserID, string tweet) {
            return base.Channel.TweetSendAsync(UserID, tweet);
        }
        
        public MVCTwitter.ServiceTweet.GetTweets_Result1[] TweetView(int ID) {
            return base.Channel.TweetView(ID);
        }
        
        public System.Threading.Tasks.Task<MVCTwitter.ServiceTweet.GetTweets_Result1[]> TweetViewAsync(int ID) {
            return base.Channel.TweetViewAsync(ID);
        }
    }
}
