//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTwitter.ServiceUser {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUsers_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFTwitter")]
    [System.SerializableAttribute()]
    public partial class GetUsers_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUser.IUserOperations")]
    public interface IUserOperations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserOperations/Login", ReplyAction="http://tempuri.org/IUserOperations/LoginResponse")]
        int Login(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserOperations/Login", ReplyAction="http://tempuri.org/IUserOperations/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserOperations/PasswordChange", ReplyAction="http://tempuri.org/IUserOperations/PasswordChangeResponse")]
        bool PasswordChange(int ID, string CurrentPassword, string NewPassoword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserOperations/PasswordChange", ReplyAction="http://tempuri.org/IUserOperations/PasswordChangeResponse")]
        System.Threading.Tasks.Task<bool> PasswordChangeAsync(int ID, string CurrentPassword, string NewPassoword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserOperations/PasswordChangeMailSend", ReplyAction="http://tempuri.org/IUserOperations/PasswordChangeMailSendResponse")]
        bool PasswordChangeMailSend(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserOperations/PasswordChangeMailSend", ReplyAction="http://tempuri.org/IUserOperations/PasswordChangeMailSendResponse")]
        System.Threading.Tasks.Task<bool> PasswordChangeMailSendAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserOperations/SignUp", ReplyAction="http://tempuri.org/IUserOperations/SignUpResponse")]
        bool SignUp(string Name, string Surname, string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserOperations/SignUp", ReplyAction="http://tempuri.org/IUserOperations/SignUpResponse")]
        System.Threading.Tasks.Task<bool> SignUpAsync(string Name, string Surname, string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserOperations/UsernameCreate", ReplyAction="http://tempuri.org/IUserOperations/UsernameCreateResponse")]
        bool UsernameCreate(int userID, string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserOperations/UsernameCreate", ReplyAction="http://tempuri.org/IUserOperations/UsernameCreateResponse")]
        System.Threading.Tasks.Task<bool> UsernameCreateAsync(int userID, string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserOperations/GetUsers", ReplyAction="http://tempuri.org/IUserOperations/GetUsersResponse")]
        MVCTwitter.ServiceUser.GetUsers_Result[] GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserOperations/GetUsers", ReplyAction="http://tempuri.org/IUserOperations/GetUsersResponse")]
        System.Threading.Tasks.Task<MVCTwitter.ServiceUser.GetUsers_Result[]> GetUsersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserOperationsChannel : MVCTwitter.ServiceUser.IUserOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserOperationsClient : System.ServiceModel.ClientBase<MVCTwitter.ServiceUser.IUserOperations>, MVCTwitter.ServiceUser.IUserOperations {
        
        public UserOperationsClient() {
        }
        
        public UserOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Login(string Email, string Password) {
            return base.Channel.Login(Email, Password);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string Email, string Password) {
            return base.Channel.LoginAsync(Email, Password);
        }
        
        public bool PasswordChange(int ID, string CurrentPassword, string NewPassoword) {
            return base.Channel.PasswordChange(ID, CurrentPassword, NewPassoword);
        }
        
        public System.Threading.Tasks.Task<bool> PasswordChangeAsync(int ID, string CurrentPassword, string NewPassoword) {
            return base.Channel.PasswordChangeAsync(ID, CurrentPassword, NewPassoword);
        }
        
        public bool PasswordChangeMailSend(string Email) {
            return base.Channel.PasswordChangeMailSend(Email);
        }
        
        public System.Threading.Tasks.Task<bool> PasswordChangeMailSendAsync(string Email) {
            return base.Channel.PasswordChangeMailSendAsync(Email);
        }
        
        public bool SignUp(string Name, string Surname, string Email, string Password) {
            return base.Channel.SignUp(Name, Surname, Email, Password);
        }
        
        public System.Threading.Tasks.Task<bool> SignUpAsync(string Name, string Surname, string Email, string Password) {
            return base.Channel.SignUpAsync(Name, Surname, Email, Password);
        }
        
        public bool UsernameCreate(int userID, string Username) {
            return base.Channel.UsernameCreate(userID, Username);
        }
        
        public System.Threading.Tasks.Task<bool> UsernameCreateAsync(int userID, string Username) {
            return base.Channel.UsernameCreateAsync(userID, Username);
        }
        
        public MVCTwitter.ServiceUser.GetUsers_Result[] GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<MVCTwitter.ServiceUser.GetUsers_Result[]> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
    }
}
